import pyautogui
import webbrowser
import time
url = 'https://forms.office.com/r/S8Jy6Jsvmh'
webbrowser.get('C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s').open(url)
time.sleep(10)
time.sleep(1)
pyautogui.click(100, 100)
time.sleep(2)
pyautogui.click(x=349, y = 486, clicks = 1)
pyautogui.scroll(-200)
time.sleep(1)
pyautogui.click(x=351, y = 560, clicks = 1)
refran = "Camaron que se duerme amanece coctel :*"
pyautogui.typewrite(refran)
time.sleep(1)
pyautogui.scroll(-450)
time.sleep(1)
pyautogui.click(x=361, y = 347, clicks = 1)
time.sleep(1)
pyautogui.click(x=369, y = 421, clicks = 1)
time.sleep(1)
pyautogui.click(x=354, y = 504, clicks = 1)
pyautogui.typewrite("holapolinesios")
pyautogui.keyDown('altright')
pyautogui.keyDown('q')
pyautogui.keyUp('altright')
pyautogui.keyUp('q')
pyautogui.typewrite("gmail.com")
pyautogui.click(x=378, y = 602, clicks = 1)
time.sleep(3)
pyautogui.click(x=352, y = 499, clicks = 1)
pyautogui.click(100, 100)
time.sleep(2)
pyautogui.click(x=342, y = 556, clicks = 1)
pyautogui.scroll(-200)
time.sleep(1)
pyautogui.click(x=351, y = 560, clicks = 1)
frase = "Asustado, Potter?"
pyautogui.typewrite(frase)
time.sleep(1)
pyautogui.scroll(-450)
time.sleep(1)
pyautogui.click(x=361, y = 347, clicks = 1)
time.sleep(1)
pyautogui.click(x=378, y = 514, clicks = 1)
time.sleep(1)
pyautogui.click(x=354, y = 504, clicks = 1)
pyautogui.typewrite("hogwarts")
pyautogui.keyDown('altright')
pyautogui.keyDown('q')
pyautogui.keyUp('altright')
pyautogui.keyUp('q')
pyautogui.typewrite("gmail.com")
pyautogui.click(x=378, y = 602, clicks = 1)
time.sleep(3)
